function(add_head_path target dir)
    target_include_directories(${target} INTERFACE ${CMAKE_SOURCE_DIR}/${dir})
    message(STATUS "path: ${dir}/${child}")
    file(GLOB children
        RELATIVE ${CMAKE_SOURCE_DIR}/${dir}
        ${CMAKE_SOURCE_DIR}/${dir}/*
    )
    list(FILTER children EXCLUDE REGEX "^\\.")
    foreach(child ${children})
    if(IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${dir}/${child}")
            message(STATUS "path: ${dir}/${child}")
            target_include_directories(${target} INTERFACE ${CMAKE_SOURCE_DIR}/${dir}/${child})
            add_head_path(${target} "${dir}/${child}")
        endif()
    endforeach()
endfunction()

function(exclude_files target)
    set(target_sources_type SOURCES)
    get_target_property(target_type ${target} TYPE)
    if(target_type STREQUAL "INTERFACE_LIBRARY")
        set(target_sources_type INTERFACE_SOURCES)
    endif()
    get_target_property(target_sources ${target} ${target_sources_type})
    set(exclude_patterns ${ARGN})
    foreach(pattern IN LISTS exclude_patterns)
        list(FILTER target_sources EXCLUDE REGEX "${pattern}")
    endforeach()
    set_target_properties(${target} PROPERTIES ${target_sources_type} "${target_sources}")
    message(STATUS "Excluded files from '${target}': ${exclude_patterns}")
endfunction()

function(add_src_path target extension path)
    file(GLOB_RECURSE files ${path}/*.${extension})
    foreach(file ${files})
        target_sources(${target} INTERFACE ${file})
        file(RELATIVE_PATH rel_path "${CMAKE_SOURCE_DIR}" "${file}")
        message(STATUS "src: ${rel_path}")
    endforeach()
endfunction()