function(add_head_path target dir)
    target_include_directories(${target} INTERFACE ${CMAKE_SOURCE_DIR}/${dir})
    message(STATUS "path: ${dir}/${child}")
    file(GLOB children
        RELATIVE ${CMAKE_SOURCE_DIR}/${dir}
        ${CMAKE_SOURCE_DIR}/${dir}/*
    )
    list(FILTER children EXCLUDE REGEX "^\\.")
    foreach(child ${children})
    if(IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${dir}/${child}")
            message(STATUS "path: ${dir}/${child}")
            target_include_directories(${target} INTERFACE ${CMAKE_SOURCE_DIR}/${dir}/${child})
            add_head_path(${target} "${dir}/${child}")
        endif()
    endforeach()
endfunction()

function(exclude_files target)
    get_target_property(target_sources ${target} SOURCES)
    if(NOT target_sources)
        return()
    endif()
    set(exclude_patterns ${ARGN})
    if(NOT exclude_patterns)
        return()
    endif()
    foreach(pattern IN LISTS exclude_patterns)
        list(FILTER target_sources EXCLUDE REGEX "${pattern}")
    endforeach()
    set_target_properties(${target} PROPERTIES SOURCES "${target_sources}")
    message(STATUS "Excluded files from ${target}: ${ARGN}")
endfunction()

function(add_src_path target extension path)
    file(GLOB_RECURSE files ${path}/*.${extension})
    foreach(file ${files})
        target_sources(${target} INTERFACE ${file})
        file(RELATIVE_PATH rel_path "${CMAKE_SOURCE_DIR}" "${file}")
        message(STATUS "src: ${rel_path}")
    endforeach()
endfunction()